version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=your-secret-key
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery
  celery:
    build: .
    command: celery -A geospatial_app worker --loglevel=info
    volumes:
      - .:/app
      - ./media:/app/media
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"